### ISSUE TITLE
Query for table fails

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oedialect#30] opened 2020-03-04 19:09 UTC
Found another bug/error using `oedialect` and `saio`:

Query:
`from saio.model_draft import bnetza_mastr_rli_v2_2_0_wind_clean as MastrWind`
```python
Session = sessionmaker(bind=engine)
session = Session()
try:
    df_mastr_wind = saio.as_pandas(session.query(MastrWind))
    session.commit()
    print('Querry successful!')
except Exception as e:
    session.rollback()
    raise
    print('Querry incomplete!')
finally:
    session.close()
```

Error:
`ParseException: Invalid HEX char`
```python
WKBReadingError                           Traceback (most recent call last)
<ipython-input-57-56f790d6c9dd> in <module>
      2 session = Session()
      3 try:
----> 4     df_mastr_wind = saio.as_pandas(session.query(MastrWind))
      5     session.commit()
      6     print('Querry successful!')
\lib\site-packages\saio.py in as_pandas(query, index_col, coerce_float, params, geometry, crs, hex_encoded)
    208         srid = getattr(obj, 'srid', -1)
    209         if srid == -1:
--> 210             srid = shapely.geos.lgeos.GEOSGetSRID(load_geom(obj)._geom)
    211 
    212         if crs is None and srid != 0:
\lib\site-packages\saio.py in <lambda>(s)
    204             load_geom = lambda s: shapely.wkb.loads(s, hex=hex_encoded)
    205         else:
--> 206             load_geom = lambda s: shapely.wkb.loads(str(s), hex=hex_encoded)
    207 
    208         srid = getattr(obj, 'srid', -1)
\lib\site-packages\shapely\wkb.py in loads(data, hex)
     13     reader = WKBReader(lgeos)
     14     if hex:
---> 15         return reader.read_hex(data)
     16     else:
     17         return reader.read(data)
\lib\site-packages\shapely\geos.py in read_hex(self, data)
    439         if not geom:
    440             raise WKBReadingError(
--> 441                 "Could not create geometry because of errors "
    442                 "while reading input.")
    443         # avoid circular import dependency
WKBReadingError: Could not create geometry because of errors while reading input.
```

**Comment by jh-RLI** [comment] 2020-03-08 22:36
The error is triggered in saio, I would suggest to move the issue. @Ludee might be possible because pandas need a 'none' value instead of 'null'.

**Comment by christian-rli** [comment] 2020-03-25 15:07
@jh-RLI is this issue solved? It does not seem to be a problem anymore on my machine and on @Ludee 's windows machine. However the same error still occured on @Izzet91 's linux machine. 
I was unable to reproduce this. 

His saio, oedialect, pandas and geopandas were up to date. I ran the same code with his credentials to draw data from the OEDB - without any problem. He's now trying to solve the problem by installing it on a new linux virtual machine - which is a nasty workaround.

Maybe you can figure out the problem with @Izzet91 . If the virtual machine doesn't work, I'm out of ideas.

**Comment by jh-RLI** [comment] 2020-03-27 16:22
It's still a problem on my end. It could be the package versions. Could you come up with a list of your packages @christian-rli or  @Ludee

**Comment by Ludee** [comment] 2020-03-27 19:23
I compared the involved packages (python, oedialect, shapely) manually and they are identical.
We could not reproduce the error on any other machine. Seems haunted ;)

**Comment by coroa** [comment] 2020-03-29 06:21
Sounds like something that at least could be worked around by saio. I would need the actual hexstring that is causing that for you. The easiest way to get something like that is to enter `%debug` in ipython or jupyter notebook after you get the exception. Go up in the stack using the command `u` until you are at the `load_geom` line in saio and then enter `p s` to print the variable `s`.

Help for the python debugger is at https://docs.python.org/3/library/pdb.html. Have fun

**Comment by jh-RLI** [comment] 2020-03-29 23:42
I tried that too but can't really tell where it comes from on my side because I get another bug. Finally I can try again tomorrow to reproduce the error on another pc. 
Additionally, I think the original problem is solved ("zero" values in table), and this is another problem. Maybe  @Izzet91 should post the error code here.

**Comment by coroa** [comment] 2020-03-30 07:34
I just released a new version of saio (v0.2.1) that treats NULL values in the geometry column properly. So, I'd propose to close this ticket and open a new one with whatever problems remain.

**Comment by Izzet91** [comment] 2020-04-01 12:51
i am getting the following error code:
![Error1](https://user-images.githubusercontent.com/54808467/78138841-dab40980-7427-11ea-871b-af2dc69d5598.png)
![Error2](https://user-images.githubusercontent.com/54808467/78138902-ef909d00-7427-11ea-9596-d0a3f43184b6.png)

**Comment by jh-RLI** [comment] 2020-04-01 13:02
This is the same error I get. @Izzet91

**Comment by jh-RLI** [comment] 2020-09-03 15:53
@KirannBhavaraju  I think this is fixed now I can't reproduce it anymore.

**Closed by jh-RLI** 2020-09-03 15:53 UTC
Labels: bug, help wanted
